name: Firebase Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2.7.0  # Replace with the latest version

      - name: Set up Node.js
        uses: actions/setup-node@v5  # Replace with the latest version
        with:
          node-version: '20'

      - name: Print Current Directory
        run: |
          echo "Current directory before CD: $(pwd)"
          
      - name: Navigate to Tyran Alexander directory
        run: cd "Tyran Alexander"

      - name: Print Current Directory After CD
        run: |
          echo "Current directory after CD: $(pwd)"
          
      - name: Install Dependencies
        run: npm install

      - name: Configure Git
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"

      - name: Firebase Deploy
        run: npm run deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
