name: Firebase Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2.7.0  # Replace with the latest version that supports Node.js 20

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Add other steps as needed...

      - name: Firebase Deploy
        run: npm run deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
